[features]
seeds = false
skip-lint = false

[programs.localnet]
mockwork = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
user = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "admin.json"

[scripts]
test = "cargo run --release"
